// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: "config.gradle"

buildscript {
    //apply from: 'https://raw.githubusercontent.com/hss01248/flipperUtil/gradle7_5/remote3.gradle?a=7'
    //apply from: 'https://raw.githubusercontent.com/hss01248/flipperUtil/dev/deps/depsLastestChecker.gradle'
    apply from: 'https://raw.githubusercontent.com/hss01248/flipperUtil/dev/z_config/git_branch_info.gradle'
    repositories {
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        mavenLocal()
        mavenCentral()
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url 'https://www.jitpack.io' }
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
